# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ""
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, "README.rst")
if os.path.exists(readme_path):
    with open(readme_path, "rb") as stream:
        readme = stream.read().decode("utf8")

setup(
    long_description=readme,
    name="git-networkx",
    version="1.2",
    description="Git graph to networkx",
    python_requires="==3.*,>=3.6.0",
    project_urls={"homepage": "https://github.com/CircArgs/git-graph"},
    author="Nick Ouellet",
    author_email="nick@ouellet.dev",
    license="MIT",
    keywords="git directed acyclic graph dag graphviz dot",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    packages=["git_graph"],
    package_dir={"": "."},
    package_data={},
    install_requires=["flake8"],
    extras_require={
        "dev": [
            "black==19.*,>=19.10.0.b0",
            "dephell==0.*,>=0.8.3",
            "pylint==2.*,>=2.5.2",
            "pytest==3.*,>=3.0.0",
            "pytest-cov==2.*,>=2.4.0",
        ]
    },
)
